---
title: Clark Weckmann
baseurl: "/"
desc: A minimal blog for all of my notes and projects, enjoy.
about: My name is Clark Weckmann, and I have a problem - self hosting.
image: https://cdn.weckmann.me/me.png
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-sitemap
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
